apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-jobflow
  labels:
    app: ai-jobflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-jobflow
  template:
    metadata:
      labels:
        app: ai-jobflow
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ai-jobflow
          image: ghcr.io/cat-shoulders/ai-jobflow:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '250m'
              memory: '256Mi'
          envFrom:
            - secretRef:
                name: ai-jobflow
          env:
            - name: ENV
              value: production
