apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml
images:
  - name: ghcr.io/cat-shoulders/ai-jobflow
    newTag: $(IMAGE_TAG)
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: ai-jobflow
    literals: []
